### ISSUE TITLE
I am an angry minecraft user

### ISSUE THREAD

**Issue by Akhali-Bri** [krysppy/icreatively3#2]
hallo server stafff rawr xDDD

My name iz baconloverally17228
I wood lik to be staff on ur server creativlyy 

i 11 and a haf yearz old and hav never been band befor!!
i used 2 be co owner on my frend xcool_guy_ronaldx2738 s sever but ita gone now :(
i will be nice to every1 and ban the hacjers XDDD
i wana b friendz wuth staff and be mean to the bad peeps!!

no i do not hav a micofone my dog broke it and idk what discod iz XD

i hope u will chooz me to be staff!!

**Comment by Akhali-Bri** [comment]
In retrospect, I really should have adjusted the title before posting. It really ruins the validity of the comment.

**Comment by krysppy** [comment]
Accepted

**Comment by krysppy** [comment]
Do you have snapchat

**Comment by Akhali-Bri** [comment]
allyizawesom788 XDD

**Comment by krysppy** [comment]
let me hit you up with my boy Dreamkazper 😃

**Comment by Akhali-Bri** [comment]
doz that mean im staff now??!! YAY

**Comment by krysppy** [comment]
youre a problem

**Comment by Akhali-Bri** [comment]
D:
